### ISSUE TITLE
Sizers are broken after recent change

### ISSUE THREAD

**Issue by 0xShortCircuit** [rexrainbow/phaser3-rex-notes#351]
The change made 2 hours ago appears to have crashed our app.  Sizers no longer work properly.  Getting errors saying .onClickOutside() is not a function of a sizer.

Also seeing this everywhere: 

phaser.js:313 Uncaught TypeError: Cannot read properties of undefined (reading 'prototype')
    at Function.mixin (phaser.js:313:5)
    at <anonymous>:1:43145
    at <anonymous>:1:202
    at <anonymous>:1:206
    at ScenePluginFile.onProcess (phaser.js:216999:1)
    at LoaderPlugin.nextFile (phaser.js:216999:1)
    at ScenePluginFile.onLoad (phaser.js:10881:5)

Is there a recommended set of changes we need to make to be compatible with the latest changes here?

**Comment by 0xShortCircuit** [comment]
Reverting to version 1.1.85 has resolved this for us, but 1.1.86 still throws the above mentioned errors.

**Comment by rexrainbow** [comment]
Latest version is `1.60.0`, for phaser3.60.0.

**Comment by 0xShortCircuit** [comment]
Right, 1.1.86 should be 1.60.0 in my previous comment.  Got it, thanks.  We're on phaser 3.55.2.  Must be the issue.  I'll test again after upgrading phaser to 3.6.0.
